sudo: false
language: python
python:
  - "3.6"

install:
  - pip install -U pip
  - pip install codecov
  - pip install .

script:
  - coverage run -m pytest
  - coverage report

after_success:
  - codecov
